name: Run XAutomaticPosting

on:
  schedule:
    # 8 runs from ~10:00 to ~22:00 CET (Berlin time), adjusted to UTC
    - cron: '7 9 * * *'    # 09:07 UTC = 10:07 CET
    - cron: '42 10 * * *'  # 10:42 UTC = 11:42 CET
    - cron: '19 12 * * *'  # 12:19 UTC = 13:19 CET
    - cron: '55 13 * * *'  # 13:55 UTC = 14:55 CET
    - cron: '33 15 * * *'  # 15:33 UTC = 16:33 CET
    - cron: '12 17 * * *'  # 17:12 UTC = 18:12 CET
    - cron: '48 18 * * *'  # 18:48 UTC = 19:48 CET
    - cron: '25 21 * * *'  # 21:25 UTC = 22:25 CET
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-posting:
    runs-on: ubuntu-latest
    container:
      image: your-dockerhub-username/xautomaticposting:latest
    env:
      TERM: xterm-256color
      NEWS_API_ORG_KEY: ${{ secrets.NEWS_API_ORG_KEY }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      X_API_KEY: ${{ secrets.X_API_KEY }}
      X_API_SECRET_KEY: ${{ secrets.X_API_SECRET_KEY }}
      OAUTH_TOKEN: ${{ secrets.OAUTH_TOKEN }}
      OAUTH_TOKEN_SECRET: ${{ secrets.OAUTH_TOKEN_SECRET }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run XAutomaticPosting script
        run: python XAutomaticPosting.py
